apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-gateway
  namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: file-gateway
  template:
    metadata:
      labels:
        app: file-gateway
    spec:
      containers:
        - name: file-gateway
          image: uhub.service.ucloud.cn/entropypool/file-gateway:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/FileGateway
          env:
            - name: ENV_ENVIRONMENT_TARGET
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.target
            - name: ENV_CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_host
            - name: ENV_CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_port
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: service-config
          configMap:
            name: file-gateway-config
            items:
              - key: service-conf
                path: FileGateway.viper.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: file-gateway
  namespace: kube-system
spec:
  ports:
    - name: pub_http
      port: 60151
      targetPort: 60151
    - name: pub_grpc
      port: 60152
      targetPort: 60152
    - name: http
      port: 60330
      targetPort: 60330
    - name: grpc
      port: 60331
      targetPort: 60331
    - name: healthz
      port: 60332
      targetPort: 60332
    - name: prometheus
      port: 60333
      targetPort: 60333
  selector:
    app: file-gateway
