apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: file-gateway-traefik-app-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: file-gateway-traefik-app
    k8s.kuboard.cn/workload: file-gateway-traefik-app
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-strip-file-gateway-prefix@kubernetescrd,
      kube-system-http-redirect-https@kubernetescrd,
      kube-system-common-headers@kubernetescrd

spec:
  tls:
    - hosts:
        - '*.hk.testnet-archimedes.blobgateway.com'
        - 'hk.testnet-archimedes.blobgateway.com'
      secretName: hk-testnet-archimedes-blobgateway-com-tls
  rules:
    - host: hk.testnet-archimedes.blobgateway.com
      http: &http_rules
        paths:
          - path: /api/file/v1/upload
            backend:
              serviceName: file-gateway
              servicePort: 60330
          - path: /api/file/v1/images
            backend:
              serviceName: file-gateway
              servicePort: 60151
